version: "3.9"

services:
  app:
    build: .
    container_name: techpines-test-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: techpines_api
      DB_USERNAME: root
      DB_PASSWORD: senha
      REDIS_HOST: redis
      REDIS_PORT: 6379

  mysql:
    image: mysql:8.0.43
    container_name: laravel-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: techpines_api
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  dbdata: